# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/faraday/all/faraday.rbi
#
# faraday-0.17.6

module Faraday
end
module Faraday::Utils
  extend Faraday::Utils
end
class Faraday::Utils::Headers < Hash
end
class Faraday::Utils::ParamsHash < Hash
end
class Faraday::Options < Struct
end
class Faraday::RequestOptions < Anonymous_Faraday_Options_48
end
class Faraday::SSLOptions < Anonymous_Faraday_Options_49
end
class Faraday::ProxyOptions < Anonymous_Faraday_Options_50
  extend Forwardable
end
class Faraday::ConnectionOptions < Anonymous_Faraday_Options_51
end
class Faraday::Env < Anonymous_Faraday_Options_52
  extend Forwardable
end
class Faraday::Connection
  extend Forwardable
end
class Faraday::RackBuilder
end
class Faraday::RackBuilder::StackLocked < RuntimeError
end
class Faraday::RackBuilder::Handler
end
module Faraday::NestedParamsEncoder
end
module Faraday::FlatParamsEncoder
end
class Faraday::Middleware
  extend Faraday::MiddlewareRegistry
end
class Faraday::Adapter < Faraday::Middleware
  extend Faraday::Adapter::Parallelism
  extend Faraday::AutoloadHelper
end
module Faraday::Adapter::Parallelism
end
class Faraday::Request < Anonymous_Struct_53
  extend Faraday::AutoloadHelper
  extend Faraday::MiddlewareRegistry
end
class Faraday::Response
  extend Faraday::AutoloadHelper
  extend Faraday::MiddlewareRegistry
  extend Forwardable
end
class Faraday::Response::Middleware < Faraday::Middleware
end
class Faraday::CompositeReadIO
end
module Faraday::DeprecatedClass
end
module Faraday::Deprecate
end
class Faraday::Error < StandardError
end
class Faraday::ClientError < Faraday::Error
end
class Faraday::BadRequestError < Faraday::ClientError
end
class Faraday::UnauthorizedError < Faraday::ClientError
end
class Faraday::ForbiddenError < Faraday::ClientError
end
class Faraday::ResourceNotFound < Faraday::ClientError
end
class Faraday::ProxyAuthError < Faraday::ClientError
end
class Faraday::ConflictError < Faraday::ClientError
end
class Faraday::UnprocessableEntityError < Faraday::ClientError
end
class Faraday::ServerError < Faraday::Error
end
class Faraday::TimeoutError < Faraday::ClientError
end
class Faraday::NilStatusError < Faraday::ServerError
  extend Faraday::Deprecate
end
class Faraday::ConnectionFailed < Faraday::ClientError
end
class Faraday::SSLError < Faraday::ClientError
end
class Faraday::ParsingError < Faraday::ClientError
end
class Faraday::RetriableResponse < Faraday::ClientError
end
class Faraday::Error::ClientError < Faraday::ClientError
end
class Faraday::Error::ConnectionFailed < Faraday::ConnectionFailed
end
class Faraday::Error::ResourceNotFound < Faraday::ResourceNotFound
end
class Faraday::Error::ParsingError < Faraday::ParsingError
end
class Faraday::Error::TimeoutError < Faraday::TimeoutError
end
class Faraday::Error::SSLError < Faraday::SSLError
end
class Faraday::Error::RetriableResponse < Faraday::RetriableResponse
end
module Faraday::AutoloadHelper
end
module Faraday::MiddlewareRegistry
end
class Faraday::Request::UrlEncoded < Faraday::Middleware
end
class Faraday::Request::Multipart < Faraday::Request::UrlEncoded
end
class Faraday::Response::RaiseError < Faraday::Response::Middleware
end
