# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/multipart-post/all/multipart-post.rbi
#
# multipart-post-2.4.1

module Multipart
end
module Multipart::Post
end
module Multipart::Post::Parts
end
module Multipart::Post::Parts::Part
end
class Multipart::Post::Parts::ParamPart
  include Multipart::Post::Parts::Part
end
class Multipart::Post::Parts::FilePart
  include Multipart::Post::Parts::Part
end
class Multipart::Post::Parts::EpiloguePart
  include Multipart::Post::Parts::Part
end
class Multipart::Post::CompositeReadIO
end
module Multipart::Post::Multipartable
end
class Multipart::Post::UploadIO
end
