# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/multi_json/all/multi_json.rbi
#
# multi_json-1.15.0

module MultiJson
  extend MultiJson
  include MultiJson::Options
end
module MultiJson::Options
end
class MultiJson::Version
end
class MultiJson::AdapterError < ArgumentError
end
class MultiJson::ParseError < StandardError
end
module MultiJson::OptionsCache
  extend MultiJson::OptionsCache
end
